# Generated by Django 2.1.15 on 2021-10-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_type', models.CharField(max_length=25)),
                ('product_description', models.TextField()),
                ('affilliate_url', models.SlugField(blank=True, null=True)),
                ('product_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
